site_name: SECP256k2
site_description: 'Documentation for SECP256k2'
site_author: 'Pymmdrza@gmail.com'
repo_url: 'https://github.com/secp256k2/secp256k2'

nav:
    - Home: index.md
    - Use in Windows: '#windows'
    - Use in Linux/Mac: '#linux--mac'
    - Git: '#git'
    - document: 'https://github.com/secp256k2/secp256k2'
    - Bug Tracking: 'https://github.com/secp256k2/secp256k2/issues'
    - Pull Requests: 'https://github.com/secp256k2/secp256k2/pulls'
    - Source: 'https://github.com/secp256k2/secp256k2'
    - Example: 'https://github.com/secp256k2/secp256k2/tree/main/Example'
    - From Private Key: 'https://github.com/secp256k2/secp256k2/blob/main/Example/PrivateKey.py'
    - From Mnemonic: 'https://github.com/secp256k2/secp256k2/blob/main/Example/Mnemonic.py'
    - From Decimal: 'https://github.com/secp256k2/secp256k2/blob/main/Example/Decimal.py'
    - From Wif: 'https://github.com/secp256k2/secp256k2/blob/main/Example/Wif.py'
    - Mmdrza.Com: 'https://mmdrza.com'
validation:
  nav:
    omitted_files: info
    not_found: warn
    absolute_links: info
  links:
    not_found: warn
    absolute_links: info
    unrecognized_links: info
theme:
  name: readthedocs
  locale: en
  collapse_by_default: false
  include_homepage_in_sidebar: true
  features:
    - navigation.tabs
    - navigation.instant

plugins:
  - search:
      indexing: 'full'

markdown_extensions:
  - smarty
  - toc:
      permalink: true
      separator: "-"
  - sane_lists

docs_dir: './docs'
